# Generated by Django 4.1.7 on 2023-03-03 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0002_direction_semestrstudyplan_sciencestudyplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(verbose_name='Malakaviy amaliyot vaqti')),
                ('semestr_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_plan.semestrstudyplan', verbose_name='Semestr rejasini tanlang')),
            ],
            options={
                'verbose_name': 'Malakaviy amaliyot',
                'verbose_name_plural': '5. Malakaviy amaliyotlar',
            },
        ),
    ]
