# Generated by Django 4.1.7 on 2023-03-03 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CafedraManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Kafedra manageri',
                'verbose_name_plural': '1. Kafedra managerlari',
            },
        ),
        migrations.CreateModel(
            name='Cafedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Fakultet nomi')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafedra.cafedramanager', verbose_name='Fakultet manageri')),
            ],
            options={
                'verbose_name': 'Kafedra',
                'verbose_name_plural': '2. Kafedralar',
            },
        ),
    ]
