# Generated by Django 4.1.7 on 2023-03-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafedra', '0003_cafedra'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafedramanager',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cafedra',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Kafedra nomi'),
        ),
    ]
